<a href="https://colab.research.google.com/github/rushikeshnaik779/tensorflow-basics/blob/main/t1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [4]:
# initilization of tensors 
x = tf.constant(4.0)
print(x)

tf.Tensor(4.0, shape=(), dtype=float32)


In [5]:
# initilization of tensors 
x = tf.constant(4, shape=(1, 1))
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [6]:
# initilization of tensors 
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [7]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
x = tf.ones((3, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [9]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [10]:
# Identity Matrix 
x = tf.eye(4)
print(x)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [11]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 2.2574894  -0.31310213 -0.6866599 ]
 [-1.3566     -0.02261231  0.55892587]
 [ 1.4384173   1.0468225  -1.0071033 ]], shape=(3, 3), dtype=float32)


In [13]:
x = tf.random.uniform((1, 3,), minval=0, maxval=1)
print(x)

tf.Tensor([[0.2634039  0.0839119  0.16840446]], shape=(1, 3), dtype=float32)


In [17]:
x = tf.range(9, 20)
print(x)

tf.Tensor([ 9 10 11 12 13 14 15 16 17 18 19], shape=(11,), dtype=int32)


In [23]:
x = tf.range(start=-1, limit=10, delta=2)
print(x)
x = tf.cast(x, dtype=tf.float64)
print(x)


tf.Tensor([-1  1  3  5  7  9], shape=(6,), dtype=int32)
tf.Tensor([-1.  1.  3.  5.  7.  9.], shape=(6,), dtype=float64)


In [24]:
# Mathematical Operations

x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
print(x+y)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [25]:
z = tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [26]:
z = tf.subtract(x,y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [27]:
print(x-y)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [28]:
print(x/y)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [29]:
print(tf.divide(x,y))

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [30]:
print(tf.multiply(x, y))

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [34]:
print(tf.tensordot(x, y, axes=1))


tf.Tensor(46, shape=(), dtype=int32)


In [35]:
print(tf.tensordot(x, y, axes=0))


tf.Tensor(
[[ 9  8  7]
 [18 16 14]
 [27 24 21]], shape=(3, 3), dtype=int32)


In [36]:
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [37]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3,4))
z = tf.matmul(x, y)
print(z)

print(x @ y)

tf.Tensor(
[[-0.6079414   1.6798015  -1.1876253  -0.47771615]
 [-0.6127246  -2.1270082   1.2845176  -0.5791465 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.6079414   1.6798015  -1.1876253  -0.47771615]
 [-0.6127246  -2.1270082   1.2845176  -0.5791465 ]], shape=(2, 4), dtype=float32)


In [42]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [43]:
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [48]:
indices = tf.constant([0,1,2,3 ,4])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 1 1 2 3], shape=(5,), dtype=int32)


In [49]:
x = tf.constant([[1, 2], 
                 [3, 4],
                 [5, 6]])

print(x)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [51]:
print(x[1:,:])

tf.Tensor(
[[3 4]
 [5 6]], shape=(2, 2), dtype=int32)


In [52]:
x = tf.range(9)
print(x)

x = tf.reshape(x, (3, 3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
